### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by nordicdyno** [keltia/leftpad#3]
we could do better!

**Comment by peterbourgon** [comment]
What is missing? Go natively supports unicode.

**Comment by nordicdyno** [comment]
but this library doesn't https://github.com/keltia/leftpad/blob/master/leftpad.go#L33

**Comment by keltia** [comment]
We could indeed create a rune version.

**Comment by peterbourgon** [comment]
Ah, fixed (I think) in my PR #4

**Comment by keltia** [comment]
Merged, thanks :)
